MvcMusicStore-Completed/MvcMusicStore/Models/Album.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using System.Collections.Generic;

namespace MvcMusicStore.Models
{
    [Bind(Exclude = "AlbumId")]
    public class Album
    {
        [ScaffoldColumn(false)]
        public int AlbumId { get; set; }

        [DisplayName("Genre")]
        public int GenreId { get; set; }

        [DisplayName("Artist")]
        public int ArtistId { get; set; }

        [Required(ErrorMessage = "An Album Title is required")]
        [StringLength(160)]
        public string Title { get; set; }

        [Required(ErrorMessage = "Price is required")]
        [Range(0.01, 100.00,
            ErrorMessage = "Price must be between 0.01 and 100.00")]
        public decimal Price { get; set; }

        [DisplayName("Album Art URL")]
        [StringLength(1024)]
        public string AlbumArtUrl { get; set; }

        public virtual Genre Genre { get; set; }
        public virtual Artist Artist { get; set; }
        public virtual List<OrderDetail> OrderDetails { get; set; }

        public virtual List<AlbumReview> AlbumReviews { get; set; }
    }
}

MvcMusicStore-Completed/MvcMusicStore/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using MvcMusicStore.Models;

namespace MvcMusicStore.Controllers
{
    public class AlbumController : Controller
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();
        // GET: Album
        [Authorize(Roles = "user")]
        public ActionResult Index()
        {
            return View(storeDB.Artists.ToList());
        }
       // [OptionalAuthorize(true)]
        [Authorize(Roles = "admin")]
        public ActionResult Edit(int id)
        {
            var album = storeDB.Artists.Find(id);
            return View(album);
        }

        //
        // GET: /Album/Export
        //[Authorize(Roles = "user")]
        public ActionResult Export()
        {
            var exportList = storeDB.Artists.ToList();
            GridView gv=new GridView();
            gv.DataSource = storeDB.Artists.ToList();
            gv.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment ; filename = Book1.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "";
            StringWriter sw=new StringWriter();
            HtmlTextWriter htw=new HtmlTextWriter(sw);
            gv.RenderControl(htw);
            Response.Output.Write(sw.ToString());
            Response.Flush();
            Response.End();
            return RedirectToAction("Index");
        }

        //
        // Post: /Album/Edit
        [HttpPost]
        public ActionResult Edit(Artist Albums)
        {
            storeDB.Entry(Albums).State = System.Data.EntityState.Modified;
            storeDB.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            storeDB.Dispose();
            base.Dispose(disposing);
        }
    }
}

MvcMusicStore-Completed/MvcMusicStore/Views/Album/Edit.cshtml

@{
    ViewBag.Title = "Edit";
}

@model MvcMusicStore.Models.Artist

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Person</legend>

        @Html.HiddenFor(model => model.ArtistId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>



MvcMusicStore-Completed/MvcMusicStore/Views/Album/Export.cshtml
@using MvcMusicStore.Models
@model IEnumerable<MvcMusicStore.Models.Artist>
@{
    ViewBag.Title = "Export";
}
<!DOCTYPE html>
<h2>All Employee Details</h2>
@foreach (Artist artist in @Model)
{
    <table style="border-collapse: collapse;" border="1">
        <tbody>
            <tr>
                <td>
                    @artist.ArtistId
                </td>
                <td>
                    @artist.Name

                </td>
            </tr>
        </tbody>
    </table>
}


MvcMusicStore-Completed/MvcMusicStore/Views/Album/Index.cshtml
@model IEnumerable<MvcMusicStore.Models.Artist>
@{
    ViewBag.Title = "Index";
}

<div id="DivGrid">
    @{
        var grid = new WebGrid(source: Model);
        @grid.GetHtml(htmlAttributes: new { id = "DataTable" }, columns: grid.Columns(
                          grid.Column("ArtistId"),
        grid.Column("Name"),  
        grid.Column("", header: "Edit", format: @<text>@Html.ActionLink("Edit", "Edit", "Album", new { id = item.ArtistId }, new { target = "_blank" })</text>),
            grid.Column("",header:"Export",format:@<text>@Html.ActionLink("Export","Export","Album")</text>)
        ));
    }

</div>

