MvcMusicStore-Completed/MvcMusicStore/Controllers/ShoppingCartController.cs
using System.Linq;
using System.Web.Mvc;
using MvcMusicStore.Models;
using MvcMusicStore.ViewModels;

namespace MvcMusicStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();

        //
        // GET: /ShoppingCart/

        public ActionResult Index()
        {
            if (Session["Logged"] == null && Request.Cookies["AuthToken"] == null)
                return RedirectToAction("LogOn", "Account");
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            // Return the view
            return View(viewModel);
        }

        //
        // GET: /Store/AddToCart/5

        public ActionResult AddToCart(int id)
        {

            // Retrieve the album from the database
            var addedAlbum = storeDB.Albums
                .Single(album => album.AlbumId == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            cart.AddToCart(addedAlbum);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5

        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the album to display confirmation
            string albumName = storeDB.Carts
                .Single(item => item.RecordId == id).Album.Title;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(albumName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };

            return Json(results);
        }

        //
        // GET: /ShoppingCart/CartSummary

        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();

            return PartialView("CartSummary");
        }
    }
}

MvcMusicStore-Completed/MvcMusicStore/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcMusicStore.Models;

namespace MvcMusicStore.Controllers
{
    public class StoreController : Controller
    {
        MusicStoreEntities storeDB = new MusicStoreEntities();

        //
        // GET: /Store/

        public ActionResult Index()
        {
            if (Session["Logged"] == null && Request.Cookies["AuthToken"] == null)
                return RedirectToAction("LogOn", "Account");
            var genres = storeDB.Genres.ToList();

            return View(genres);
        }

        //SQL injection
        // GET: /Store/Browse?genre=Disco
        public ActionResult Search(string searchStr)
        {
            DataTable dt = new DataTable();
            string connString = storeDB.Database.Connection.ConnectionString;
           // string query = string.Format("select * from [Album] where Title like '%{0}'", searchStr);
            string query = "select * from [Albums] where Title like @TitleName+'%' ";
            string str = searchStr.Substring(0, 3);
            try
            {             
                using (SqlConnection connection = new SqlConnection(connString))
                {
                    connection.Open();
                    SqlCommand cmd = new SqlCommand(query, connection);
                    cmd.Parameters.Add(new SqlParameter("TitleName", str));
                    // SqlDataAdapter da = cmd.ExecuteReader();
                    SqlDataAdapter da = new SqlDataAdapter(cmd);
                    da.Fill(dt);
                    connection.Close();
                }

            }
            catch (Exception ex)
            {


            }
            ViewBag.Data = dt;
            return View();
        }

        //
        // GET: /Store/Browse?genre=Disco

        public ActionResult Browse(string genre)
        {
            if (Session["Logged"] == null && Request.Cookies["AuthToken"] == null)
                return RedirectToAction("LogOn", "Account");
            // Retrieve Genre and its Associated Albums from database
            var genreModel = storeDB.Genres.Include("Albums")
                .Single(g => g.Name == genre);

            return View(genreModel);
        }

        //
        // GET: /Store/Details/5

        public ActionResult Details(int id)
        {
            var album = storeDB.Albums.Find(id);
            //throw new ApplicationException("Testing default ErrorHandler attribute");
            return View(album);
        }

        //
        // GET: /Store/GenreMenu

        [ChildActionOnly]
        public ActionResult GenreMenu()
        {
            var genres = storeDB.Genres.ToList();

            return PartialView(genres);
        }

    }
}

MvcMusicStore-Completed/MvcMusicStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet"
          type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")"
            type="text/javascript"></script>
    <style type="text/css">
        #search {
            width: 300px;
            float: right;
            display: block;
            margin-top: 21px;
            padding-left: 230px;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div id="header">
        <h1><a href="/">GRAND MUSIC STORE</a></h1>
        <div>
            <div style="display: block;">
                <ul id="navlist">
                    <li class="first"><a href="@Url.Content("~")" id="current">Home</a></li>
                    <li><a href="@Url.Content("~/Secure/")">Profile</a></li>
                    <li><a href="@Url.Content("~/Store/")">Store</a></li>
                    <li>@{Html.RenderAction("CartSummary", "ShoppingCart");}</li>
                    <li><a href="@Url.Content("~/StoreManager/")">Admin</a></li>
                    @if (HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString() == "Secure")
                    {
                        <li><a href="@Url.Content("~/Account/LogOff")">Sign Out</a></li>
                    }
                    <li><a href="@Url.Content("~/Demo/")">Demo</a></li>
                    <li><a href="@Url.Content("~/Album/")">Album</a></li>
                   
                </ul>
            </div>
            <div id="search">
                <form action="@Url.Action("Search", "Store")">
                    <input type="text" name="searchStr" style="width: 200px;height: 26px;" />
                    <input type="submit" value="Search" />
                </form>
            </div>
            @if (User.Identity.Name != "")
            {
                <h3 style="float: right">Welcome : @User.Identity.Name</h3>
            }
        </div>
    </div>


    @{Html.RenderAction("GenreMenu", "Store");}

    <div id="main">
        @RenderBody()
    </div>

    <div id="footer">
        Sonata Software
    </div>
</body>
</html>